server.port=3001
spring.application.name=flight-compare-app

spring.datasource.url=jdbc:postgresql://localhost:5432/flightdb
spring.datasource.username=postgres
spring.datasource.password=123Saxena
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.flightapp=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

